// SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: MPL-2.0

package dto

import "time"

type RawAny Raw[any]

// raw data message as generated by data collectors and stored in the mongodb
type Raw[Rawtype any] struct {
	Provider  string    `json:"provider"`
	Timestamp time.Time `json:"timestamp"`
	Rawdata   Rawtype   `json:"rawdata"`
}

// Data write notifications generated by the MongoDB Notifier
type Notification struct {
	Id         string
	Db         string
	Collection string
	Urn        string
}
